LAB_DESCRIPTION="NGN SDN Firewall + MQTT"

# Controller
ctrl[0]="MGMT"
ctrl[image]="ngn-sdn-firewall-ctrl"
ctrl[mount0]="../shared:/shared"
ctrl[num_terms]=1
ctrl[bridged]=false

# Switch SDN
s1[0]="MGMT"
s1[1]="INT_C1"
s1[2]="INT_C2"
s1[3]="INT_C3"
s1[4]="INT_MQTT"
s1[5]="EXT_A1"
s1[6]="EXT_A2"
s1[7]="EXT_A3"
s1[image]="kathara/sdn"
s1[num_terms]=1
s1[bridged]=false

# Interni
h_c1[0]="INT_C1/02:00:00:10:00:11"
h_c2[0]="INT_C2/02:00:00:10:00:12"
h_c3[0]="INT_C3/02:00:00:10:00:13"
h_c1[image]="ngn-host-tools"
h_c2[image]="ngn-host-tools"
h_c3[image]="ngn-host-tools"

# MQTT interno
h_mqtt[0]="INT_MQTT/02:00:00:10:00:20"
h_mqtt[image]="ngn-sdn-firewall-mqtt"

# Esterni (attacker)
h_a1[0]="EXT_A1/02:00:00:20:00:31"
h_a2[0]="EXT_A2/02:00:00:20:00:32"
h_a3[0]="EXT_A3/02:00:00:20:00:33"
h_a1[image]="ngn-host-tools"
h_a2[image]="ngn-host-tools"
h_a3[image]="ngn-host-tools"

