LAB_DESCRIPTION="NGN SDN Firewall + MQTT"

# Controller Ryu
ctrl[0]="MGMT"
ctrl[image]="ngn-sdn-firewall-ctrl"
ctrl[mount0]="../shared:/shared"

# Switch SDN (Open vSwitch + Ryu installato nell'immagine)
s1[0]="MGMT"
s1[1]="LAN_CLIENT"
s1[2]="LAN_MQTT"
s1[3]="LAN_OUT"
s1[image]="kathara/sdn"

# Host interno (client)
h_client[0]="LAN_CLIENT"

# Host che farà da MQTT broker
h_mqtt[0]="LAN_MQTT"
h_mqtt[image]="ngn-sdn-firewall-mqtt"


# "Internet" / host esterno
h_out[0]="LAN_OUT"

h_client[image]="ngn-host-tools"
h_out[image]="ngn-host-tools"


